Repository HyoZaSon/FrontEnd, pull requests merged in 2023-08, with the labels that each got.

#10 [FEAT] 메인 화면 추가, GlobalStyle 추가, 반응형 컴포넌트 추가
  src/App.jsx
  src/index.jsx
  src/pages/Main.jsx
  src/pages/index.js
  src/shared/GlobalStyle.jsx
  src/shared/MediaQuery.jsx
  src/shared/Router.js
Labels: 이혜영, UI, FEAT

#11 [UI] 도움을 받는 사람 화면
  src/pages/Hyozaparent.jsx
Labels: 이혜영, UI

#12 [UI] 모달창 추가, 로딩중 화면 추가
  src/components/Hyozaparent/Connect.jsx
  src/components/Hyozaparent/Modal.jsx
  src/img/loading.png
  src/pages/Hyozaparent.jsx
  src/pages/Loading.jsx
  src/pages/index.js
  src/shared/Router.js
Labels: 이혜영, UI

#15 [UI] 도움 주는 사람(효자손) 메인 페이지 화면
  src/pages/Hyozason.jsx
Labels: 정서연, UI

#19 [UI] 평가 페이지 화면 구성
  package-lock.json
  package.json
  src/pages/Evaluation.jsx
Labels: 이혜영, UI

#20 [UI] 헤더 UI 구현
  public/index.html
  public/logo.ico
  src/img/loading.gif
  src/img/logo.svg
  src/pages/Evaluation.jsx
  src/pages/Hyozaparent.jsx
  src/pages/Loading.jsx
  src/shared/GlobalStyle.jsx
  src/shared/Header.jsx
Labels: 이혜영, UI

#22 [Feat] 도움 버튼 클릭시 위치 받아오기
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/pages/Hyozaparent.jsx
Labels: 이혜영, FEAT

#23 [Refactor] 코드 리팩토링
  src/components/Hyozaparent/Connect.jsx
  src/components/Hyozaparent/HelpBox.jsx
  src/components/Hyozaparent/HelpBtn.jsx
  src/components/Hyozaparent/Modal.jsx
  src/components/Hyozaparent/ModalHelp.jsx
  src/components/Hyozaparent/ModalLoading.jsx
  src/pages/Hyozaparent.jsx
  src/pages/Loading.jsx
  src/shared/Router.js
Labels: 이혜영

#26 [Refactor] 평가 페이지 화면 수정
  src/pages/Evaluation.jsx
Labels: 이혜영, UI

#38 [Feat] 회원가입 오류 수정
  src/components/Register/PhoneNumber.jsx
  src/components/Register/Region.jsx
  src/pages/Register.jsx
  src/shared/Header.jsx
Labels: FEAT

#43 [FEAT] 도움주는 사람 메인 페이지
  src/pages/Hyozason.jsx
Labels: 정서연, FEAT
